name: Print URL

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The URL to download'
        required: true

jobs:
  print-url:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg p7zip-full python3-pip
          pip3 install yt-dlp

      - name: Create output directory
        run: mkdir -p output

      - name: Download from URL
        run: yt-dlp -v -f "bestvideo[height<=720]+bestaudio/best[height<=720]" --merge-output-format mkv -o "output/%(title)s.%(ext)s" "${{ github.event.inputs.url }}"

      - name: Zip it up
        run: 7z a -p123 -mhe=on -mx=0 Video0.7z ./output/*

      - name: Generate tag from date/time
        id: tagger
        shell: bash
        run: |
          echo "tag=v$(date +'%Y-%m-%d_%H-%M-%S')" >> "$GITHUB_OUTPUT"
          echo "body=$(ls output | tr '\n' ' ')" >> "$GITHUB_OUTPUT"

      - name: Upload to GitHub Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tagger.outputs.tag }}
          name: "New Porn Video"
          body: ${{ steps.tagger.outputs.body }}
          files: Video0.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                     "username": "Release Bot",
                     "avatar_url": "https://i.ibb.co.com/CPrt4Dg/1732257842387.jpg",
                     "content": "**New Release Published!** 🚀",
                     "embeds": [{
                       "title": "New Porn Video",
                       "url": "${{ steps.release.upload_url }}",
                       "description": "${{ steps.tagger.outputs.body }}",
                       "color": 5814783
                     }]
                   }' \
               $WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
