name: Print URL

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The URL to download'
        required: true

jobs:
  print-url:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg p7zip-full python3-pip
          pip3 install yt-dlp

      - name: Create output directory
        run: mkdir -p output

      - name: Download from URL
        run: yt-dlp -v -f "bestvideo[height<=720]+bestaudio/best[height<=720]" --merge-output-format mkv -o "output/%(title)s.%(ext)s" "${{ github.event.inputs.url }}"

      - name: Zip it up
        run: 7z a -p123 -mhe=on -mx=0 Video0.7z ./output/*

      - name: Generate tag from date/time
        id: tagger
        run: |
          echo "tag=v$(date +'%Y-%m-%d_%H-%M-%S')" >> "$GITHUB_OUTPUT"
          echo "body=$(ls output)" >> "$GITHUB_OUTPUT"

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ setps.tagger.outputs.tag }}
          name: ${{ setps.tagger.outputs.body }}
          body: ${{ setps.tagger.outputs.body }}
          files: Video0.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
