name: Print URL

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The URL to print'
        required: true
        default: 'https://example.com'

jobs:
  print-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: install ffmpeg
        run: sudo apt update; sudo apt install ffmpeg

      - name: install yt-dlp
        run: pip install yt-dlp

      - name: Download from url
        run: yt-dlp -v -f "bestvideo[height<=720]+bestaudio/best[height<=720]" --merge-output-format mkv -o "output/%(title)s.%(ext)s" "${{ github.event.inputs.url }}"

      - name: upload
        run: python upload.py
